version: "3.7"
services:
  backend:
    build: backend
    ports: 
      - 80
    volumes:
      - type: volume
        source: www
        target: /var/www/html/
      - type: volume
        source: apache2
        target: /etc/apache2
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
  daemon:
    build: daemon
    volumes:
      - type: volume
        source: www
        target: /var/www/html/
      - type: volume
        source: apache2
        target: /etc/apache2
      - type: volume
        source: etc_letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: varlib_letsencrypt
        target: /var/lib/letsencrypt

volumes:
  www:
  apache2:
  etc_letsencrypt:
  varlib_letsencrypt:
